### ISSUE TITLE
Random notifications

### ISSUE THREAD

**Issue by DuoDex** [sandsmark/QuasselDroid#276] opened 2016-07-26 13:24 UTC
On my Android Marshmallow HTC One A9, Quasseldroid occasionally creates irrelevant notifications of PMs I've already read.

Using v0.11.7 from F-Droid.

**Comment by fraxinas** [comment] 2016-09-18 18:54
Same Issue on OnePlus 2.
So far I haven't understood any scheme in which the notifications pop up. Sometimes it can be chats that had happened months ago!

**Comment by bauerj** [comment] 2016-09-21 18:56
Same here.

**Comment by justjanne** [comment] 2016-09-21 21:39
The issue is mostly a race condition, if the client receives messages before having fully processed which buffers are already read or not.

By default, the markerline is set to 0, so any message ever received will be assumed is "new".

I’ve looked into fixing it for quite a while already.

**Comment by wjp** [comment] 2016-10-14 22:38
I think I tracked this down to a specific race. Possible solution at PR #278 .

**Comment by ojwb** [comment] 2017-02-21 03:08
#278 was merged back in October so this can presumably be closed now (and thanks very much for addressing this).

**Closed** 2017-02-22 11:24 UTC
