### ISSUE TITLE
Certificate issue with new Android N beta

### ISSUE THREAD

**Issue by kevinbenton** [sandsmark/QuasselDroid#274] opened 2016-05-22 05:39 UTC
I installed the Android N beta and quasseldroid is not compatible with the new version due to a certificate store error when attempting to connect. It can't seem to retrieve the cached certificate or store the new certificate from the server on connect attempt so it never successfully connects to a server. The error is below:

> The core SSL-Certificate has changed, do you trust the new one? 
> java.lang.RuntimeException: Failed to load certificates from KeyStore

**Comment by justjanne** [comment] 2016-05-22 19:53
Android N has broken a lot of things, and I’ll probably have to change a lot of things. Thanks for the report, though, I’ll look into it (once I can get my hands on something that can run Android N)

**Comment by kevinbenton** [comment] 2016-05-22 22:30
No worries. I figured as much and just opted out of the beta for now. Just
figured I would report the bug for an early warning. :)

**Comment by bobobo1618** [comment] 2016-07-25 05:43
Hopefully more helpful, here's the tracebacks I see repeated over and over again when I try to connect:

```
07-24 22:21:30.417   854   854 I CoreConnService: Service created
07-24 22:21:30.422   854   854 I CoreConnService: Connecting to core: host:4242 with username user
07-24 22:21:30.423   854  1395 I CoreConnection: Connecting...
07-24 22:21:30.768   854  1395 I CoreConnection: Attempting new-style handshake...
07-24 22:21:31.299   854  1395 D CoreConnection: Using compression.
07-24 22:21:31.299   854  1395 I CoreConnection: Sending client info...
07-24 22:21:31.303   854  1395 I CoreConnection: Getting core info...
07-24 22:21:31.941   854  1395 D CoreConnection: Using SSL.
07-24 22:21:31.945   854  1395 I CoreConnection: Starting SSL handshake...
07-24 22:21:32.276   854  1395 W CoreConnection: Got IOException while connecting
07-24 22:21:32.276   854  1395 W CoreConnection: Got CertificateException while connecting
07-24 22:21:32.278   854  1395 W CoreConnection: IOException while closing outStream
07-24 22:21:32.278   854  1395 W CoreConnection: java.net.SocketException: Socket closed
07-24 22:21:32.278   854  1395 W CoreConnection:    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:120)
07-24 22:21:32.278   854  1395 W CoreConnection:    at java.net.SocketOutputStream.write(SocketOutputStream.java:157)
07-24 22:21:32.278   854  1395 W CoreConnection:    at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:254)
07-24 22:21:32.278   854  1395 W CoreConnection:    at java.util.zip.DeflaterOutputStream.finish(DeflaterOutputStream.java:227)
07-24 22:21:32.278   854  1395 W CoreConnection:    at java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:239)
07-24 22:21:32.278   854  1395 W CoreConnection:    at java.io.FilterOutputStream.close(FilterOutputStream.java:160)
07-24 22:21:32.278   854  1395 W CoreConnection:    at com.iskrembilen.quasseldroid.io.CoreConnection$ReadThread.run(CoreConnection.java:828)
07-24 22:21:32.350   878  5407 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@5002f1f attribute=null, token = android.os.BinderProxy@5037210
07-24 22:21:32.354   854   854 I CoreConnService: Destroying service
07-24 22:21:32.568   878   898 I WindowManager: Destroying surface Surface(name=com.iskrembilen.quasseldroid/com.iskrembilen.quasseldroid.gui.LoginActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.AppWindowToken.destroySurfaces:363 com.android.server.wm.WindowStateAnimator.finishExit:565 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:491 com.android.server.wm.WindowAnimator.updateWindowsLocked:303 com.android.server.wm.WindowAnimator.animateLocked:704
07-24 22:21:49.464  4048  4476 I ClearcutLoggerApiImpl: disconnect managed GoogleApiClient
07-24 22:21:55.883   854   854 E SQLiteDatabase: Error inserting certificate=java.lang.RuntimeException: Failed to load certificates from KeyStore coreid=1
07-24 22:21:55.883   854   854 E SQLiteDatabase: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: certificates.coreid (code 2067)
07-24 22:21:55.883   854   854 E SQLiteDatabase:    at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
07-24 22:21:55.883   854   854 E SQLiteDatabase:    at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
07-24 22:21:55.883   854   854 E SQLiteDatabase:    at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
07-24 22:21:55.883   854   854 E SQLiteDatabase:    at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
07-24 22:21:55.883   854   854 E SQLiteDatabase:    at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1472)
07-24 22:21:55.883   854   854 E SQLiteDatabase:    at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1343)
--
07-24 22:20:54.214   854   854 E SQLiteDatabase:    at com.iskrembilen.quasseldroid.gui.LoginActivity$4.onClick(LoginActivity.java:310)
07-24 22:20:54.214   854   854 E SQLiteDatabase:    at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:164)
07-24 22:20:54.214   854   854 E SQLiteDatabase:    at android.os.Handler.dispatchMessage(Handler.java:102)
07-24 22:20:54.214   854   854 E SQLiteDatabase:    at android.os.Looper.loop(Looper.java:154)
07-24 22:20:54.214   854   854 E SQLiteDatabase:    at android.app.ActivityThread.main(ActivityThread.java:6077)
07-24 22:20:54.214   854   854 E SQLiteDatabase:    at java.lang.reflect.Method.invoke(Native Method)
07-24 22:20:54.214   854   854 E SQLiteDatabase:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
07-24 22:20:54.214   854   854 E SQLiteDatabase:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by heftig** [comment] 2016-08-23 14:55
I've had this error in the old version distributed via the Play store but not after I installed 0.11.7.

**Comment by dmick** [comment] 2016-08-25 02:03
Confirmed, the Play Store version is broken; I don't know how to install anything later

**Comment by justjanne** [comment] 2016-08-25 21:44
@dmick:

We currently have an updated version in the F-Droid store, or directly available from my buildserver’s build listing at https://dl.kuschku.de/releases/quasseldroid/

Build 140 is what you'd want.

58b2cdb775cb096a94f2f517a8d75380480dfa121cd596ce5398c00dcb891930  QuasselDroid-kuschku-release-0.11.6-build140.apk

**Comment by dmick** [comment] 2016-08-25 22:00
@justjanne: thanks.  That version works.

**Comment by ski7777** [comment] 2016-09-03 20:39
Works,

After install I had to add my core again, but works fine.

Raphael

**Comment by jeremyvisser** [comment] 2016-09-18 00:09
I could reproduce the issue as described in comment 1 on the Play Store version. After upgrading to the latest F-Droid version, I can confirm the issue is now fixed.

**Comment by mrjester888** [comment] 2016-09-18 23:54
Same issue.  5x + Android 7.  Installing the 0.11.7-build160 resolved it.

**Comment by justjanne** [comment] 2016-10-17 00:25
As the new version is now on the Play Store, I’ll close this now.

**Closed by justjanne** 2016-10-17 00:25 UTC
